language: objective-c
osx_image: xcode7.2
notifications:
  email:
    on_success: change 
    on_failure: always
branches:
  only:
    - master
    - develop
before_script: cd Student
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script: 
- xctool -project Student.xcodeproj -scheme Student -destination "name=iPad Air 2" -sdk iphonesimulator
- xctool test -project Student.xcodeproj -scheme Student -destination "name=iPad Air 2" -sdk iphonesimulator