language: objective-c
osx_image: xcode7.3
notifications:
  email:
    on_success: change
    on_failure: always
branches:
  only:
    - master
    - develop
before_script: cd app
script:
- fastlane test
