language: objective-c
osx_image: xcode7.2.1 
xcode_project: Student.xcodeproj 
xcode_scheme: Student 
xcode_sdk: iphonesimulator9.1
notifications:
  email:
    on_success: change 
    on_failure: always
before_script: cd Student
before_install:
  - brew update
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
script: 
- xctool -project Student.xcodeproj -scheme Student -sdk iphonesimulator
- xctool test -project Student.xcodeproj -scheme Student -sdk iphonesimulator
